on:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release Action
        uses: dkaser/unraid-plugin-release-action@main
        id: release_action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_dir: "tsidp"
          build_script: |
            cd tsidp
            ./build.sh
